set -g @thm_bg '#2E3440'
set -g @thm_fg '#D8DEE9'

set -g @thm_session_bg '#5E81AC'
set -g @thm_session_fg '#2E3440'

set -g @thm_right_bg '#4C566A'
set -g @thm_right_fg '#ECEFF4'

set -g @thm_machine_bg '#88C0D0'
set -g @thm_machine_fg '#2E3440'

set -g @thm_win_active_bg '#81A1C1'
set -g @thm_win_active_fg '#2E3440'
set -g @thm_win_inactive_bg '#3B4252'
set -g @thm_win_inactive_fg '#D8DEE9'

set -g @thm_pane_active '#81A1C1'
set -g @thm_pane_inactive '#4C566A'

set -g @thm_msg_bg '#A3BE8C'
set -g @thm_msg_fg '#2E3440'
set -g @thm_mode_bg '#EBCB8B'
set -g @thm_mode_fg '#2E3440'
