set -g @thm_bg '#1f2335'
set -g @thm_fg '#7aa2f7'

set -g @thm_session_bg '#9ece6a'
set -g @thm_session_fg '#1d202f'

set -g @thm_right_bg '#3b4261'
set -g @thm_right_fg '#7aa2f7'

set -g @thm_machine_bg '#bb9af7'
set -g @thm_machine_fg '#1d202f'

set -g @thm_win_active_bg '#3b4261'
set -g @thm_win_active_fg '#7aa2f7'
set -g @thm_win_inactive_bg '#1f2335'
set -g @thm_win_inactive_fg '#a9b1d6'

set -g @thm_pane_active '#7aa2f7'
set -g @thm_pane_inactive '#3b4261'

set -g @thm_msg_bg '#3b4261'
set -g @thm_msg_fg '#7aa2f7'
set -g @thm_mode_bg '#3b4261'
set -g @thm_mode_fg '#7aa2f7'
