format = """
[░▒▓](#a3aed2)\
$username\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
$docker_context\
[](fg:#394260 bg:#212736)\
$c\
$elixir\
$elm\
$nodejs\
$rust\
$lua\
$golang\
$java\
$julia\
$php\
$python\
[ ](fg:#212736)"""

# Disable the blank line at the start of the prompt
add_newline = false

[username]
show_always = true
style_user = "bg:#a3aed2 fg:#090c0c"
style_root = "bg:#a3aed2"
format = '[$user ]($style)'
disabled = false 

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[docker_context]
symbol = " "
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = " "
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = " "
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = " "
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = " "
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

