#!/bin/bash

root_folder=${PWD}
main_file=""
session_name="default"


info(){
    printf "Usage: $0 [-n NAME] [-t] [-d FOLDER] [-f FILE] [-h]\\n";
    printf "\\t-n\\tNAME for the session to open\\n"
    printf "\\t-t\\tAdd and extra test window\\n"
    printf "\\t-d\\tSet the FOLDER where the proyect is\\n"
    printf "\\t-f\\tOpen the FILE to edit insside vim\\n"
    printf "\\t-h\\tDisplay this help\\n"
}

 while getopts ":d:f:thn:" o; do
     case "${o}" in
       d)
            root_folder=$OPTARG
            ;;
       f)
            main_file=$OPTARG
            ;;
       n)
           session_name=$OPTARG
           ;;
       t)
             fl_test="test"
            ;;
         *)
             info && exit
             ;;
     esac
 done


# Cambiar al directorio especificado
cd "$root_folder" || { echo "Directory not found: $root_folder"; exit 1; }

# Verificar si la sesión ya existe
if tmux has-session -t "$session_name" 2>/dev/null; then
    echo "Session '$session_name' already exists. Attaching..."
    tmux attach-session -t "$session_name"
else
    echo "Creating new session '$session_name'..."
    tmux new-session -s "$session_name" -d "vim $main_file"
    tmux split-window -h -l 1% 'htop'
    tmux split-window -v -l 99%
    tmux split-window -v

    if [ -n "$fl_test" ]; then
        tmux new-window -t "$session_name":1 -n "$fl_test"
        tmux split-window -h 'btm'
    fi

    tmux select-window -t "$session_name":0
    tmux select-pane -t 0
    tmux attach-session -t "$session_name"
fi
